appName: myhelmapp

port: 80

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This sample application was deployed with helm!'

image:
  name: devopsjourney1/mywebapp
  tag: latest